---
- name: Install Docker, Kubernetes CLI, Helm, and Jenkins
  hosts: devops_server
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - openjdk-17-jdk
        state: present

    # -----------------------
    # Docker
    # -----------------------
    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash

    - name: Add current user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # -----------------------
    # kubectl
    # -----------------------
    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
      args:
        executable: /bin/bash

    # -----------------------
    # Helm
    # -----------------------
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash

    # -----------------------
    # Jenkins
    # -----------------------
    - name: Add Jenkins GPG key and repo
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
          /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
          https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
          /etc/apt/sources.list.d/jenkins.list > /dev/null
      args:
        executable: /bin/bash

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started
